FROM ubuntu:22.04

RUN apt update
RUN apt install -y git wget openjdk-21-jre-headless

COPY files/build.sh /spigot-build/
COPY files/mcenv.sh /spigot-build/

RUN mkdir /spigot-build/output
WORKDIR /spigot-build
