FROM ubuntu:22.04

RUN apt update
RUN apt install -y git wget openjdk-21-jre-headless

COPY files/run.sh /spigot/
COPY files/mcenv.sh /spigot/
COPY build/spigot*.jar /spigot/
RUN echo "eula=true" > "/spigot/eula.txt"

WORKDIR /spigot

EXPOSE 25565/tcp
EXPOSE 25565/udp
EXPOSE 25575/tcp
EXPOSE 25575/udp
